/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dae_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[138] = {26, 24, 0, 7, 14, 21, 30, 39, 48, 53, 58, 63, 68, 73, 78, 81, 84, 87, 91, 95, 99, 101, 103, 105, 107, 109, 111, 12, 16, 17, 18, 21, 24, 25, 13, 15, 17, 19, 22, 24, 25, 14, 15, 16, 20, 23, 24, 25, 4, 5, 12, 16, 17, 18, 21, 24, 25, 3, 5, 13, 15, 17, 19, 22, 24, 25, 3, 4, 14, 15, 16, 20, 23, 24, 25, 12, 16, 17, 18, 24, 13, 15, 17, 19, 24, 14, 15, 16, 20, 24, 12, 16, 17, 21, 25, 13, 15, 17, 22, 25, 14, 15, 16, 23, 25, 0, 24, 25, 1, 24, 25, 2, 24, 25, 4, 5, 24, 25, 3, 5, 24, 25, 3, 4, 24, 25, 6, 24, 7, 24, 8, 24, 9, 25, 10, 25, 11, 25};
static const casadi_int casadi_s5[69] = {26, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 18, 21, 24, 27, 30, 32, 34, 36, 38, 40, 42, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 24, 25, 13, 24, 25, 14, 24, 25, 15, 24, 25, 16, 24, 25, 17, 24, 25, 18, 24, 19, 24, 20, 24, 21, 25, 22, 25, 23, 25};
static const casadi_int casadi_s6[15] = {26, 6, 0, 1, 2, 3, 4, 5, 6, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s7[23] = {26, 2, 0, 9, 18, 12, 13, 14, 15, 16, 17, 18, 19, 20, 12, 13, 14, 15, 16, 17, 21, 22, 23};

/* dae_impl_dae_jac_x_xdot_u_z:(i0[24],i1[24],i2[6],i3[2],i4[],i5[])->(o0[26x24,111nz],o1[26x24,42nz],o2[26x6,6nz],o3[26x2,18nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[3]? arg[3][1] : 0;
  a2=(a0+a1);
  if (res[0]!=0) res[0][0]=a2;
  a3=arg[0]? arg[0][5] : 0;
  a4=(a0*a3);
  a5=(a1*a3);
  a6=(a4-a5);
  if (res[0]!=0) res[0][1]=a6;
  a6=arg[0]? arg[0][4] : 0;
  a7=(a1*a6);
  a8=(a0*a6);
  a9=(a7-a8);
  if (res[0]!=0) res[0][2]=a9;
  a9=(-a0);
  if (res[0]!=0) res[0][3]=a9;
  a10=(-a1);
  if (res[0]!=0) res[0][4]=a10;
  a11=arg[1]? arg[1][12] : 0;
  a12=arg[1]? arg[1][16] : 0;
  a13=(a12*a3);
  a14=(a11+a13);
  a15=arg[1]? arg[1][17] : 0;
  a16=(a15*a6);
  a17=(a14-a16);
  a18=arg[1]? arg[1][18] : 0;
  a17=(a17-a18);
  a19=arg[0]? arg[0][15] : 0;
  a20=casadi_sq(a19);
  a21=arg[0]? arg[0][16] : 0;
  a22=casadi_sq(a21);
  a20=(a20+a22);
  a22=arg[0]? arg[0][17] : 0;
  a23=casadi_sq(a22);
  a20=(a20+a23);
  a23=arg[0]? arg[0][3] : 0;
  a24=(a20*a23);
  a25=25.;
  a26=5.0000000000000000e-01;
  a27=arg[0]? arg[0][0] : 0;
  a28=(a27+a23);
  a29=arg[0]? arg[0][6] : 0;
  a28=(a28-a29);
  a29=(a28+a28);
  a29=(a26*a29);
  a29=(a25*a29);
  a30=(a24-a29);
  a31=10.;
  a32=arg[0]? arg[0][12] : 0;
  a33=(a21*a3);
  a34=(a22*a6);
  a33=(a33-a34);
  a34=(a32+a33);
  a35=arg[0]? arg[0][18] : 0;
  a36=(a34-a35);
  a37=(a31*a36);
  a30=(a30-a37);
  a17=(a17-a30);
  if (res[0]!=0) res[0][5]=a17;
  a17=(a11-a13);
  a17=(a17+a16);
  a30=arg[1]? arg[1][21] : 0;
  a17=(a17-a30);
  a27=(a27-a23);
  a37=arg[0]? arg[0][9] : 0;
  a27=(a27-a37);
  a37=(a27+a27);
  a37=(a26*a37);
  a37=(a25*a37);
  a38=(a24+a37);
  a39=(a32-a33);
  a40=arg[0]? arg[0][21] : 0;
  a41=(a39-a40);
  a42=(a31*a41);
  a42=(a38+a42);
  a17=(a17+a42);
  if (res[0]!=0) res[0][6]=a17;
  if (res[0]!=0) res[0][7]=a2;
  a17=(a5-a4);
  if (res[0]!=0) res[0][8]=a17;
  a17=(a0*a23);
  a42=(a1*a23);
  a43=(a17-a42);
  if (res[0]!=0) res[0][9]=a43;
  if (res[0]!=0) res[0][10]=a9;
  if (res[0]!=0) res[0][11]=a10;
  a43=arg[1]? arg[1][13] : 0;
  a44=arg[1]? arg[1][15] : 0;
  a45=(a44*a3);
  a46=(a43-a45);
  a47=(a15*a23);
  a46=(a46+a47);
  a48=arg[1]? arg[1][19] : 0;
  a46=(a46-a48);
  a49=(a20*a6);
  a50=arg[0]? arg[0][1] : 0;
  a51=(a50+a6);
  a52=arg[0]? arg[0][7] : 0;
  a51=(a51-a52);
  a52=(a51+a51);
  a52=(a26*a52);
  a52=(a25*a52);
  a53=(a49-a52);
  a54=arg[0]? arg[0][13] : 0;
  a55=(a22*a23);
  a56=(a19*a3);
  a55=(a55-a56);
  a56=(a54+a55);
  a57=arg[0]? arg[0][19] : 0;
  a58=(a56-a57);
  a59=(a31*a58);
  a53=(a53-a59);
  a46=(a46-a53);
  if (res[0]!=0) res[0][12]=a46;
  a46=(a43+a45);
  a53=(a46-a47);
  a59=arg[1]? arg[1][22] : 0;
  a53=(a53-a59);
  a50=(a50-a6);
  a60=arg[0]? arg[0][10] : 0;
  a50=(a50-a60);
  a60=(a50+a50);
  a60=(a26*a60);
  a60=(a25*a60);
  a61=(a49+a60);
  a62=(a54-a55);
  a63=arg[0]? arg[0][22] : 0;
  a64=(a62-a63);
  a65=(a31*a64);
  a65=(a61+a65);
  a53=(a53+a65);
  if (res[0]!=0) res[0][13]=a53;
  if (res[0]!=0) res[0][14]=a2;
  a2=(a8-a7);
  if (res[0]!=0) res[0][15]=a2;
  a2=(a42-a17);
  if (res[0]!=0) res[0][16]=a2;
  if (res[0]!=0) res[0][17]=a9;
  if (res[0]!=0) res[0][18]=a10;
  a2=arg[1]? arg[1][14] : 0;
  a53=(a44*a6);
  a65=(a2+a53);
  a66=(a12*a23);
  a67=(a65-a66);
  a68=arg[1]? arg[1][20] : 0;
  a67=(a67-a68);
  a69=(a20*a3);
  a70=arg[0]? arg[0][2] : 0;
  a71=(a70+a3);
  a72=arg[0]? arg[0][8] : 0;
  a71=(a71-a72);
  a72=(a71+a71);
  a72=(a26*a72);
  a72=(a25*a72);
  a73=(a69-a72);
  a74=arg[0]? arg[0][14] : 0;
  a75=(a19*a6);
  a76=(a21*a23);
  a75=(a75-a76);
  a76=(a74+a75);
  a77=arg[0]? arg[0][20] : 0;
  a78=(a76-a77);
  a79=(a31*a78);
  a73=(a73-a79);
  a67=(a67-a73);
  if (res[0]!=0) res[0][19]=a67;
  a67=(a2-a53);
  a67=(a67+a66);
  a73=arg[1]? arg[1][23] : 0;
  a67=(a67-a73);
  a70=(a70-a3);
  a79=arg[0]? arg[0][11] : 0;
  a70=(a70-a79);
  a79=(a70+a70);
  a26=(a26*a79);
  a25=(a25*a26);
  a26=(a69+a25);
  a79=(a74-a75);
  a80=arg[0]? arg[0][23] : 0;
  a81=(a79-a80);
  a82=(a31*a81);
  a82=(a26+a82);
  a67=(a67+a82);
  if (res[0]!=0) res[0][20]=a67;
  a67=(-a22);
  if (res[0]!=0) res[0][21]=a67;
  if (res[0]!=0) res[0][22]=a21;
  a67=(a0-a1);
  if (res[0]!=0) res[0][23]=a67;
  a82=(a3-a71);
  a83=(a0*a82);
  a84=(a70+a3);
  a85=(a1*a84);
  a83=(a83+a85);
  if (res[0]!=0) res[0][24]=a83;
  a83=(a51-a6);
  a85=(a0*a83);
  a86=(a6+a50);
  a87=(a1*a86);
  a85=(a85-a87);
  if (res[0]!=0) res[0][25]=a85;
  if (res[0]!=0) res[0][26]=a9;
  if (res[0]!=0) res[0][27]=a1;
  a82=(a12*a82);
  a82=(a11+a82);
  a83=(a15*a83);
  a82=(a82+a83);
  a82=(a82-a18);
  a83=(a23+a28);
  a83=(a20*a83);
  a85=(a54*a22);
  a87=(a74*a21);
  a88=(a85-a87);
  a83=(a83-a88);
  a88=(a55*a22);
  a89=(a58*a22);
  a89=(a88+a89);
  a90=(a75*a21);
  a91=(a78*a21);
  a91=(a90+a91);
  a89=(a89-a91);
  a83=(a83-a89);
  a89=(a57*a22);
  a91=(a77*a21);
  a89=(a89-a91);
  a83=(a83+a89);
  a83=(a83-a29);
  a89=(a51*a22);
  a89=(a33+a89);
  a91=(a71*a21);
  a89=(a89-a91);
  a89=(a32+a89);
  a89=(a89-a35);
  a89=(a31*a89);
  a83=(a83-a89);
  a82=(a82-a83);
  if (res[0]!=0) res[0][28]=a82;
  a84=(a12*a84);
  a84=(a84-a11);
  a86=(a15*a86);
  a84=(a84-a86);
  a84=(a84+a30);
  a86=(a64*a22);
  a86=(a86-a88);
  a88=(a81*a21);
  a90=(a90-a88);
  a86=(a86+a90);
  a87=(a87-a85);
  a85=(a27-a23);
  a85=(a20*a85);
  a87=(a87+a85);
  a86=(a86-a87);
  a87=(a80*a21);
  a85=(a63*a22);
  a87=(a87-a85);
  a86=(a86+a87);
  a86=(a86+a37);
  a37=(a50*a22);
  a37=(a37-a33);
  a87=(a70*a21);
  a37=(a37-a87);
  a37=(a32+a37);
  a37=(a40-a37);
  a37=(a31*a37);
  a86=(a86-a37);
  a84=(a84-a86);
  if (res[0]!=0) res[0][29]=a84;
  if (res[0]!=0) res[0][30]=a22;
  a84=(-a19);
  if (res[0]!=0) res[0][31]=a84;
  if (res[0]!=0) res[0][32]=a67;
  a84=(a71-a3);
  a86=(a0*a84);
  a37=(a3+a70);
  a87=(a1*a37);
  a86=(a86-a87);
  if (res[0]!=0) res[0][33]=a86;
  a86=(a23-a28);
  a87=(a0*a86);
  a85=(a27+a23);
  a90=(a1*a85);
  a87=(a87+a90);
  if (res[0]!=0) res[0][34]=a87;
  if (res[0]!=0) res[0][35]=a9;
  if (res[0]!=0) res[0][36]=a1;
  a84=(a44*a84);
  a84=(a43+a84);
  a86=(a15*a86);
  a84=(a84+a86);
  a84=(a84-a48);
  a86=(a6+a51);
  a86=(a20*a86);
  a87=(a74*a19);
  a90=(a32*a22);
  a88=(a87-a90);
  a86=(a86-a88);
  a88=(a75*a19);
  a82=(a78*a19);
  a82=(a88+a82);
  a83=(a33*a22);
  a89=(a36*a22);
  a89=(a83+a89);
  a82=(a82-a89);
  a86=(a86-a82);
  a82=(a77*a19);
  a89=(a35*a22);
  a82=(a82-a89);
  a86=(a86+a82);
  a86=(a86-a52);
  a82=(a28*a22);
  a82=(a55-a82);
  a89=(a71*a19);
  a82=(a82+a89);
  a82=(a54+a82);
  a82=(a82-a57);
  a82=(a31*a82);
  a86=(a86-a82);
  a84=(a84-a86);
  if (res[0]!=0) res[0][37]=a84;
  a15=(a15*a85);
  a37=(a44*a37);
  a37=(a43+a37);
  a15=(a15-a37);
  a15=(a15+a59);
  a37=(a41*a22);
  a83=(a83-a37);
  a37=(a81*a19);
  a37=(a37-a88);
  a83=(a83+a37);
  a90=(a90-a87);
  a87=(a50-a6);
  a87=(a20*a87);
  a90=(a90+a87);
  a83=(a83-a90);
  a90=(a40*a22);
  a87=(a80*a19);
  a90=(a90-a87);
  a83=(a83+a90);
  a83=(a83+a60);
  a60=(a70*a19);
  a90=(a27*a22);
  a90=(a90+a55);
  a60=(a60-a90);
  a60=(a54+a60);
  a60=(a63-a60);
  a60=(a31*a60);
  a83=(a83-a60);
  a15=(a15-a83);
  if (res[0]!=0) res[0][38]=a15;
  a15=(-a21);
  if (res[0]!=0) res[0][39]=a15;
  if (res[0]!=0) res[0][40]=a19;
  if (res[0]!=0) res[0][41]=a67;
  a67=(a6-a51);
  a15=(a0*a67);
  a83=(a50+a6);
  a60=(a1*a83);
  a15=(a15+a60);
  if (res[0]!=0) res[0][42]=a15;
  a15=(a28-a23);
  a60=(a0*a15);
  a90=(a23+a27);
  a87=(a1*a90);
  a60=(a60-a87);
  if (res[0]!=0) res[0][43]=a60;
  if (res[0]!=0) res[0][44]=a9;
  if (res[0]!=0) res[0][45]=a1;
  a67=(a44*a67);
  a67=(a2+a67);
  a15=(a12*a15);
  a67=(a67+a15);
  a67=(a67-a68);
  a15=(a3+a71);
  a15=(a20*a15);
  a60=(a32*a21);
  a87=(a54*a19);
  a37=(a60-a87);
  a15=(a15-a37);
  a37=(a33*a21);
  a88=(a36*a21);
  a88=(a37+a88);
  a85=(a55*a19);
  a84=(a58*a19);
  a84=(a85+a84);
  a88=(a88-a84);
  a15=(a15-a88);
  a88=(a35*a21);
  a84=(a57*a19);
  a88=(a88-a84);
  a15=(a15+a88);
  a15=(a15-a72);
  a88=(a28*a21);
  a84=(a51*a19);
  a88=(a88-a84);
  a88=(a88+a75);
  a88=(a74+a88);
  a88=(a88-a77);
  a88=(a31*a88);
  a15=(a15-a88);
  a67=(a67-a15);
  if (res[0]!=0) res[0][46]=a67;
  a44=(a44*a83);
  a44=(a44-a2);
  a12=(a12*a90);
  a44=(a44-a12);
  a44=(a44+a73);
  a12=(a41*a21);
  a12=(a12-a37);
  a37=(a64*a19);
  a85=(a85-a37);
  a12=(a12+a85);
  a87=(a87-a60);
  a60=(a70-a3);
  a20=(a20*a60);
  a87=(a87+a20);
  a12=(a12-a87);
  a87=(a63*a19);
  a20=(a40*a21);
  a87=(a87-a20);
  a12=(a12+a87);
  a12=(a12+a25);
  a25=(a27*a21);
  a87=(a50*a19);
  a25=(a25-a87);
  a25=(a25-a75);
  a25=(a74+a25);
  a25=(a80-a25);
  a25=(a31*a25);
  a12=(a12-a25);
  a44=(a44-a12);
  if (res[0]!=0) res[0][47]=a44;
  if (res[0]!=0) res[0][48]=a9;
  a44=(-a4);
  if (res[0]!=0) res[0][49]=a44;
  if (res[0]!=0) res[0][50]=a8;
  if (res[0]!=0) res[0][51]=a0;
  a14=(a16-a14);
  a14=(a14+a18);
  a29=(a29-a24);
  a24=(a35-a34);
  a24=(a31*a24);
  a29=(a29-a24);
  a14=(a14-a29);
  if (res[0]!=0) res[0][52]=a14;
  if (res[0]!=0) res[0][53]=a9;
  if (res[0]!=0) res[0][54]=a4;
  a4=(-a17);
  if (res[0]!=0) res[0][55]=a4;
  if (res[0]!=0) res[0][56]=a0;
  a45=(a45-a43);
  a45=(a45-a47);
  a45=(a45+a48);
  a52=(a52-a49);
  a49=(a57-a56);
  a49=(a31*a49);
  a52=(a52-a49);
  a45=(a45-a52);
  if (res[0]!=0) res[0][57]=a45;
  if (res[0]!=0) res[0][58]=a9;
  a8=(-a8);
  if (res[0]!=0) res[0][59]=a8;
  if (res[0]!=0) res[0][60]=a17;
  if (res[0]!=0) res[0][61]=a0;
  a65=(a66-a65);
  a65=(a65+a68);
  a72=(a72-a69);
  a69=(a77-a76);
  a69=(a31*a69);
  a72=(a72-a69);
  a65=(a65-a72);
  if (res[0]!=0) res[0][62]=a65;
  if (res[0]!=0) res[0][63]=a10;
  if (res[0]!=0) res[0][64]=a5;
  a65=(-a7);
  if (res[0]!=0) res[0][65]=a65;
  if (res[0]!=0) res[0][66]=a1;
  a13=(a13-a11);
  a13=(a13-a16);
  a13=(a13+a30);
  a30=(a33-a32);
  a30=(a30+a40);
  a30=(a31*a30);
  a38=(a38-a30);
  a13=(a13-a38);
  if (res[0]!=0) res[0][67]=a13;
  if (res[0]!=0) res[0][68]=a10;
  a5=(-a5);
  if (res[0]!=0) res[0][69]=a5;
  if (res[0]!=0) res[0][70]=a42;
  if (res[0]!=0) res[0][71]=a1;
  a47=(a47-a46);
  a47=(a47+a59);
  a59=(a55-a54);
  a59=(a59+a63);
  a59=(a31*a59);
  a61=(a61-a59);
  a47=(a47-a61);
  if (res[0]!=0) res[0][72]=a47;
  if (res[0]!=0) res[0][73]=a10;
  if (res[0]!=0) res[0][74]=a7;
  a42=(-a42);
  if (res[0]!=0) res[0][75]=a42;
  if (res[0]!=0) res[0][76]=a1;
  a53=(a53-a2);
  a53=(a53-a66);
  a53=(a53+a73);
  a73=(a75-a74);
  a73=(a73+a80);
  a73=(a31*a73);
  a26=(a26-a73);
  a53=(a53-a26);
  if (res[0]!=0) res[0][77]=a53;
  a53=-1.;
  if (res[0]!=0) res[0][78]=a53;
  a26=(a32+a36);
  a26=(a26+a33);
  a26=(a35-a26);
  a73=(a31*a28);
  a26=(a26-a73);
  a26=(-a26);
  if (res[0]!=0) res[0][79]=a26;
  a26=(a32+a41);
  a26=(a33-a26);
  a26=(a26+a40);
  a66=(a31*a27);
  a26=(a26-a66);
  a26=(-a26);
  if (res[0]!=0) res[0][80]=a26;
  if (res[0]!=0) res[0][81]=a53;
  a26=(a54+a58);
  a26=(a26+a55);
  a26=(a57-a26);
  a2=(a31*a51);
  a26=(a26-a2);
  a26=(-a26);
  if (res[0]!=0) res[0][82]=a26;
  a26=(a54+a64);
  a26=(a55-a26);
  a26=(a26+a63);
  a1=(a31*a50);
  a26=(a26-a1);
  a26=(-a26);
  if (res[0]!=0) res[0][83]=a26;
  if (res[0]!=0) res[0][84]=a53;
  a26=(a74+a78);
  a26=(a26+a75);
  a26=(a77-a26);
  a42=(a31*a71);
  a26=(a26-a42);
  a26=(-a26);
  if (res[0]!=0) res[0][85]=a26;
  a26=(a74+a81);
  a26=(a75-a26);
  a26=(a26+a80);
  a7=(a31*a70);
  a26=(a26-a7);
  a26=(-a26);
  if (res[0]!=0) res[0][86]=a26;
  if (res[0]!=0) res[0][87]=a3;
  a26=(-a6);
  if (res[0]!=0) res[0][88]=a26;
  a26=(a28*a23);
  a10=(a51*a6);
  a26=(a26+a10);
  a10=(a71*a3);
  a26=(a26+a10);
  a19=(a19+a19);
  a10=(a26*a19);
  a47=(a74*a6);
  a61=(a54*a3);
  a59=(a47-a61);
  a10=(a10-a59);
  a59=(a75*a6);
  a46=(a78*a6);
  a46=(a59+a46);
  a5=(a55*a3);
  a13=(a58*a3);
  a13=(a5+a13);
  a46=(a46-a13);
  a10=(a10-a46);
  a46=(a77*a6);
  a13=(a57*a3);
  a46=(a46-a13);
  a10=(a10+a46);
  a46=(a71*a6);
  a13=(a51*a3);
  a46=(a46-a13);
  a46=(a31*a46);
  a10=(a10-a46);
  a10=(-a10);
  if (res[0]!=0) res[0][89]=a10;
  a10=(a64*a3);
  a5=(a5-a10);
  a10=(a81*a6);
  a10=(a10-a59);
  a5=(a5+a10);
  a61=(a61-a47);
  a47=(a27*a23);
  a10=(a50*a6);
  a47=(a47+a10);
  a10=(a70*a3);
  a47=(a47+a10);
  a19=(a47*a19);
  a61=(a61+a19);
  a5=(a5-a61);
  a61=(a63*a3);
  a19=(a80*a6);
  a61=(a61-a19);
  a5=(a5+a61);
  a61=(a70*a6);
  a19=(a50*a3);
  a61=(a61-a19);
  a61=(a31*a61);
  a5=(a5+a61);
  a5=(-a5);
  if (res[0]!=0) res[0][90]=a5;
  a5=(-a3);
  if (res[0]!=0) res[0][91]=a5;
  if (res[0]!=0) res[0][92]=a23;
  a21=(a21+a21);
  a5=(a26*a21);
  a61=(a32*a3);
  a74=(a74*a23);
  a19=(a61-a74);
  a5=(a5-a19);
  a19=(a33*a3);
  a10=(a36*a3);
  a10=(a19+a10);
  a75=(a75*a23);
  a59=(a78*a23);
  a59=(a75+a59);
  a10=(a10-a59);
  a5=(a5-a10);
  a10=(a35*a3);
  a59=(a77*a23);
  a10=(a10-a59);
  a5=(a5+a10);
  a10=(a28*a3);
  a59=(a71*a23);
  a10=(a10-a59);
  a10=(a31*a10);
  a5=(a5-a10);
  a5=(-a5);
  if (res[0]!=0) res[0][93]=a5;
  a5=(a41*a3);
  a5=(a5-a19);
  a19=(a81*a23);
  a75=(a75-a19);
  a5=(a5+a75);
  a74=(a74-a61);
  a21=(a47*a21);
  a74=(a74+a21);
  a5=(a5-a74);
  a74=(a80*a23);
  a21=(a40*a3);
  a74=(a74-a21);
  a5=(a5+a74);
  a74=(a27*a3);
  a21=(a70*a23);
  a74=(a74-a21);
  a74=(a31*a74);
  a5=(a5+a74);
  a5=(-a5);
  if (res[0]!=0) res[0][94]=a5;
  if (res[0]!=0) res[0][95]=a6;
  a5=(-a23);
  if (res[0]!=0) res[0][96]=a5;
  a22=(a22+a22);
  a26=(a26*a22);
  a54=(a54*a23);
  a32=(a32*a6);
  a5=(a54-a32);
  a26=(a26-a5);
  a55=(a55*a23);
  a5=(a58*a23);
  a5=(a55+a5);
  a33=(a33*a6);
  a74=(a36*a6);
  a74=(a33+a74);
  a5=(a5-a74);
  a26=(a26-a5);
  a5=(a57*a23);
  a74=(a35*a6);
  a5=(a5-a74);
  a26=(a26+a5);
  a5=(a51*a23);
  a74=(a28*a6);
  a5=(a5-a74);
  a5=(a31*a5);
  a26=(a26-a5);
  a26=(-a26);
  if (res[0]!=0) res[0][97]=a26;
  a26=(a41*a6);
  a33=(a33-a26);
  a26=(a64*a23);
  a26=(a26-a55);
  a33=(a33+a26);
  a32=(a32-a54);
  a47=(a47*a22);
  a32=(a32+a47);
  a33=(a33-a32);
  a32=(a40*a6);
  a47=(a63*a23);
  a32=(a32-a47);
  a33=(a33+a32);
  a32=(a50*a23);
  a47=(a27*a6);
  a32=(a32-a47);
  a31=(a31*a32);
  a33=(a33+a31);
  a33=(-a33);
  if (res[0]!=0) res[0][98]=a33;
  if (res[0]!=0) res[0][99]=a53;
  a36=(a36-a35);
  a34=(a34+a36);
  a34=(a34+a73);
  a34=(-a34);
  if (res[0]!=0) res[0][100]=a34;
  if (res[0]!=0) res[0][101]=a53;
  a58=(a58-a57);
  a56=(a56+a58);
  a56=(a56+a2);
  a56=(-a56);
  if (res[0]!=0) res[0][102]=a56;
  if (res[0]!=0) res[0][103]=a53;
  a78=(a78-a77);
  a76=(a76+a78);
  a76=(a76+a42);
  a76=(-a76);
  if (res[0]!=0) res[0][104]=a76;
  if (res[0]!=0) res[0][105]=a53;
  a41=(a41-a40);
  a39=(a39+a41);
  a39=(a39+a66);
  a39=(-a39);
  if (res[0]!=0) res[0][106]=a39;
  if (res[0]!=0) res[0][107]=a53;
  a64=(a64-a63);
  a62=(a62+a64);
  a62=(a62+a1);
  a62=(-a62);
  if (res[0]!=0) res[0][108]=a62;
  if (res[0]!=0) res[0][109]=a53;
  a81=(a81-a80);
  a79=(a79+a81);
  a79=(a79+a7);
  a79=(-a79);
  if (res[0]!=0) res[0][110]=a79;
  a79=1.;
  if (res[1]!=0) res[1][0]=a79;
  if (res[1]!=0) res[1][1]=a79;
  if (res[1]!=0) res[1][2]=a79;
  if (res[1]!=0) res[1][3]=a79;
  if (res[1]!=0) res[1][4]=a79;
  if (res[1]!=0) res[1][5]=a79;
  if (res[1]!=0) res[1][6]=a79;
  if (res[1]!=0) res[1][7]=a79;
  if (res[1]!=0) res[1][8]=a79;
  if (res[1]!=0) res[1][9]=a79;
  if (res[1]!=0) res[1][10]=a79;
  if (res[1]!=0) res[1][11]=a79;
  a79=4.4500000000000001e-01;
  if (res[1]!=0) res[1][12]=a79;
  if (res[1]!=0) res[1][13]=a28;
  if (res[1]!=0) res[1][14]=a27;
  if (res[1]!=0) res[1][15]=a79;
  if (res[1]!=0) res[1][16]=a51;
  if (res[1]!=0) res[1][17]=a50;
  if (res[1]!=0) res[1][18]=a79;
  if (res[1]!=0) res[1][19]=a71;
  if (res[1]!=0) res[1][20]=a70;
  a79=1.4999999999999999e-01;
  if (res[1]!=0) res[1][21]=a79;
  a7=(a6*a71);
  a81=(a3*a51);
  a7=(a7-a81);
  if (res[1]!=0) res[1][22]=a7;
  a81=(a3*a50);
  a80=(a6*a70);
  a81=(a81-a80);
  if (res[1]!=0) res[1][23]=a81;
  if (res[1]!=0) res[1][24]=a79;
  a80=(a3*a28);
  a62=(a23*a71);
  a80=(a80-a62);
  if (res[1]!=0) res[1][25]=a80;
  a62=(a23*a70);
  a3=(a3*a27);
  a62=(a62-a3);
  if (res[1]!=0) res[1][26]=a62;
  if (res[1]!=0) res[1][27]=a79;
  a79=(a23*a51);
  a3=(a6*a28);
  a79=(a79-a3);
  if (res[1]!=0) res[1][28]=a79;
  a6=(a6*a27);
  a23=(a23*a50);
  a6=(a6-a23);
  if (res[1]!=0) res[1][29]=a6;
  a23=1.2000000000000000e+00;
  if (res[1]!=0) res[1][30]=a23;
  a3=(-a28);
  if (res[1]!=0) res[1][31]=a3;
  if (res[1]!=0) res[1][32]=a23;
  a1=(-a51);
  if (res[1]!=0) res[1][33]=a1;
  if (res[1]!=0) res[1][34]=a23;
  a64=(-a71);
  if (res[1]!=0) res[1][35]=a64;
  if (res[1]!=0) res[1][36]=a23;
  a63=(-a27);
  if (res[1]!=0) res[1][37]=a63;
  if (res[1]!=0) res[1][38]=a23;
  a39=(-a50);
  if (res[1]!=0) res[1][39]=a39;
  if (res[1]!=0) res[1][40]=a23;
  a23=(-a70);
  if (res[1]!=0) res[1][41]=a23;
  if (res[2]!=0) res[2][0]=a53;
  if (res[2]!=0) res[2][1]=a53;
  if (res[2]!=0) res[2][2]=a53;
  if (res[2]!=0) res[2][3]=a53;
  if (res[2]!=0) res[2][4]=a53;
  if (res[2]!=0) res[2][5]=a53;
  if (res[3]!=0) res[3][0]=a28;
  if (res[3]!=0) res[3][1]=a51;
  if (res[3]!=0) res[3][2]=a71;
  if (res[3]!=0) res[3][3]=a7;
  if (res[3]!=0) res[3][4]=a80;
  if (res[3]!=0) res[3][5]=a79;
  if (res[3]!=0) res[3][6]=a3;
  if (res[3]!=0) res[3][7]=a1;
  if (res[3]!=0) res[3][8]=a64;
  if (res[3]!=0) res[3][9]=a27;
  if (res[3]!=0) res[3][10]=a50;
  if (res[3]!=0) res[3][11]=a70;
  if (res[3]!=0) res[3][12]=a81;
  if (res[3]!=0) res[3][13]=a62;
  if (res[3]!=0) res[3][14]=a6;
  if (res[3]!=0) res[3][15]=a63;
  if (res[3]!=0) res[3][16]=a39;
  if (res[3]!=0) res[3][17]=a23;
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dae_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dae_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dae_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void dae_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dae_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int dae_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real dae_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dae_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dae_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dae_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dae_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
