/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dae_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[30] = {26, 1, 0, 26, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
static const casadi_int casadi_s5[138] = {26, 24, 0, 7, 14, 21, 30, 39, 48, 53, 58, 63, 68, 73, 78, 81, 84, 87, 91, 95, 99, 101, 103, 105, 107, 109, 111, 12, 16, 17, 18, 21, 24, 25, 13, 15, 17, 19, 22, 24, 25, 14, 15, 16, 20, 23, 24, 25, 4, 5, 12, 16, 17, 18, 21, 24, 25, 3, 5, 13, 15, 17, 19, 22, 24, 25, 3, 4, 14, 15, 16, 20, 23, 24, 25, 12, 16, 17, 18, 24, 13, 15, 17, 19, 24, 14, 15, 16, 20, 24, 12, 16, 17, 21, 25, 13, 15, 17, 22, 25, 14, 15, 16, 23, 25, 0, 24, 25, 1, 24, 25, 2, 24, 25, 4, 5, 24, 25, 3, 5, 24, 25, 3, 4, 24, 25, 6, 24, 7, 24, 8, 24, 9, 25, 10, 25, 11, 25};
static const casadi_int casadi_s6[69] = {26, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 18, 21, 24, 27, 30, 32, 34, 36, 38, 40, 42, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 24, 25, 13, 24, 25, 14, 24, 25, 15, 24, 25, 16, 24, 25, 17, 24, 25, 18, 24, 19, 24, 20, 24, 21, 25, 22, 25, 23, 25};
static const casadi_int casadi_s7[15] = {26, 6, 0, 1, 2, 3, 4, 5, 6, 18, 19, 20, 21, 22, 23};

/* dae_impl_dae_fun_jac_x_xdot_u:(i0[24],i1[24],i2[6],i3[2],i4[],i5[])->(o0[26],o1[26x24,111nz],o2[26x24,42nz],o3[26x6,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][12] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a2=arg[0]? arg[0][13] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a3=arg[0]? arg[0][14] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a4=arg[0]? arg[0][16] : 0;
  a5=arg[0]? arg[0][5] : 0;
  a6=(a4*a5);
  a7=arg[0]? arg[0][17] : 0;
  a8=arg[0]? arg[0][4] : 0;
  a9=(a7*a8);
  a6=(a6-a9);
  a0=(a0-a6);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a9=arg[0]? arg[0][3] : 0;
  a10=(a7*a9);
  a11=arg[0]? arg[0][15] : 0;
  a12=(a11*a5);
  a10=(a10-a12);
  a0=(a0-a10);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a12=(a11*a8);
  a13=(a4*a9);
  a12=(a12-a13);
  a0=(a0-a12);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a13=arg[0]? arg[0][18] : 0;
  a0=(a0-a13);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a14=arg[0]? arg[0][19] : 0;
  a0=(a0-a14);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a15=arg[0]? arg[0][20] : 0;
  a0=(a0-a15);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][9] : 0;
  a16=arg[0]? arg[0][21] : 0;
  a0=(a0-a16);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][10] : 0;
  a17=arg[0]? arg[0][22] : 0;
  a0=(a0-a17);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a18=arg[0]? arg[0][23] : 0;
  a0=(a0-a18);
  if (res[0]!=0) res[0][11]=a0;
  a0=4.4500000000000001e-01;
  a19=arg[1]? arg[1][12] : 0;
  a20=(a0*a19);
  a21=arg[0]? arg[0][0] : 0;
  a22=(a21+a9);
  a23=arg[0]? arg[0][6] : 0;
  a22=(a22-a23);
  a23=arg[3]? arg[3][0] : 0;
  a24=(a22*a23);
  a20=(a20+a24);
  a21=(a21-a9);
  a25=arg[0]? arg[0][9] : 0;
  a21=(a21-a25);
  a25=arg[3]? arg[3][1] : 0;
  a26=(a21*a25);
  a20=(a20+a26);
  if (res[0]!=0) res[0][12]=a20;
  a20=arg[1]? arg[1][13] : 0;
  a27=(a0*a20);
  a28=arg[0]? arg[0][1] : 0;
  a29=(a28+a8);
  a30=arg[0]? arg[0][7] : 0;
  a29=(a29-a30);
  a30=(a29*a23);
  a27=(a27+a30);
  a28=(a28-a8);
  a31=arg[0]? arg[0][10] : 0;
  a28=(a28-a31);
  a31=(a28*a25);
  a27=(a27+a31);
  if (res[0]!=0) res[0][13]=a27;
  a27=arg[1]? arg[1][14] : 0;
  a32=(a0*a27);
  a33=arg[0]? arg[0][2] : 0;
  a34=(a33+a5);
  a35=arg[0]? arg[0][8] : 0;
  a34=(a34-a35);
  a35=(a34*a23);
  a32=(a32+a35);
  a33=(a33-a5);
  a36=arg[0]? arg[0][11] : 0;
  a33=(a33-a36);
  a36=(a33*a25);
  a32=(a32+a36);
  a37=4.3654500000000001e+00;
  a32=(a32-a37);
  if (res[0]!=0) res[0][14]=a32;
  a32=1.4999999999999999e-01;
  a37=arg[1]? arg[1][15] : 0;
  a38=(a32*a37);
  a39=(a8*a34);
  a40=(a5*a29);
  a39=(a39-a40);
  a40=(a39*a23);
  a38=(a38+a40);
  a40=(a5*a28);
  a41=(a8*a33);
  a40=(a40-a41);
  a41=(a40*a25);
  a38=(a38+a41);
  if (res[0]!=0) res[0][15]=a38;
  a38=arg[1]? arg[1][16] : 0;
  a41=(a32*a38);
  a42=(a5*a22);
  a43=(a9*a34);
  a42=(a42-a43);
  a43=(a42*a23);
  a41=(a41+a43);
  a43=(a9*a33);
  a44=(a5*a21);
  a43=(a43-a44);
  a44=(a43*a25);
  a41=(a41+a44);
  if (res[0]!=0) res[0][16]=a41;
  a41=arg[1]? arg[1][17] : 0;
  a44=(a32*a41);
  a45=(a9*a29);
  a46=(a8*a22);
  a45=(a45-a46);
  a46=(a45*a23);
  a44=(a44+a46);
  a46=(a8*a21);
  a47=(a9*a28);
  a46=(a46-a47);
  a47=(a46*a25);
  a44=(a44+a47);
  if (res[0]!=0) res[0][17]=a44;
  a44=1.2000000000000000e+00;
  a47=arg[1]? arg[1][18] : 0;
  a48=(a44*a47);
  a48=(a48-a24);
  a24=arg[2]? arg[2][0] : 0;
  a48=(a48-a24);
  if (res[0]!=0) res[0][18]=a48;
  a48=arg[1]? arg[1][19] : 0;
  a24=(a44*a48);
  a24=(a24-a30);
  a30=arg[2]? arg[2][1] : 0;
  a24=(a24-a30);
  if (res[0]!=0) res[0][19]=a24;
  a24=arg[1]? arg[1][20] : 0;
  a30=(a44*a24);
  a30=(a30-a35);
  a35=1.1772000000000000e+01;
  a49=arg[2]? arg[2][2] : 0;
  a49=(a35+a49);
  a30=(a30-a49);
  if (res[0]!=0) res[0][20]=a30;
  a30=arg[1]? arg[1][21] : 0;
  a49=(a44*a30);
  a49=(a49-a26);
  a26=arg[2]? arg[2][3] : 0;
  a49=(a49-a26);
  if (res[0]!=0) res[0][21]=a49;
  a49=arg[1]? arg[1][22] : 0;
  a26=(a44*a49);
  a26=(a26-a31);
  a31=arg[2]? arg[2][4] : 0;
  a26=(a26-a31);
  if (res[0]!=0) res[0][22]=a26;
  a26=arg[1]? arg[1][23] : 0;
  a31=(a44*a26);
  a31=(a31-a36);
  a36=arg[2]? arg[2][5] : 0;
  a35=(a35+a36);
  a31=(a31-a35);
  if (res[0]!=0) res[0][23]=a31;
  a31=(a22*a19);
  a35=(a29*a20);
  a31=(a31+a35);
  a35=(a34*a27);
  a31=(a31+a35);
  a35=(a39*a37);
  a31=(a31+a35);
  a35=(a42*a38);
  a31=(a31+a35);
  a35=(a45*a41);
  a31=(a31+a35);
  a35=(a22*a47);
  a31=(a31-a35);
  a35=(a29*a48);
  a31=(a31-a35);
  a35=(a34*a24);
  a31=(a31-a35);
  a35=casadi_sq(a11);
  a36=casadi_sq(a4);
  a35=(a35+a36);
  a36=casadi_sq(a7);
  a35=(a35+a36);
  a36=(a22*a9);
  a50=(a29*a8);
  a36=(a36+a50);
  a50=(a34*a5);
  a36=(a36+a50);
  a50=(a35*a36);
  a51=(a1+a6);
  a52=(a51-a13);
  a53=(a52*a1);
  a54=(a2+a10);
  a55=(a54-a14);
  a56=(a55*a2);
  a53=(a53+a56);
  a56=(a3+a12);
  a57=(a56-a15);
  a58=(a57*a3);
  a53=(a53+a58);
  a50=(a50-a53);
  a53=(a52*a6);
  a58=(a55*a10);
  a53=(a53+a58);
  a58=(a57*a12);
  a53=(a53+a58);
  a50=(a50-a53);
  a53=(a52*a13);
  a58=(a55*a14);
  a53=(a53+a58);
  a58=(a57*a15);
  a53=(a53+a58);
  a50=(a50+a53);
  a53=25.;
  a58=5.0000000000000000e-01;
  a59=casadi_sq(a22);
  a60=casadi_sq(a29);
  a59=(a59+a60);
  a60=casadi_sq(a34);
  a59=(a59+a60);
  a60=1.;
  a59=(a59-a60);
  a59=(a58*a59);
  a59=(a53*a59);
  a50=(a50-a59);
  a59=10.;
  a61=(a22*a1);
  a62=(a29*a2);
  a61=(a61+a62);
  a62=(a34*a3);
  a61=(a61+a62);
  a62=(a22*a6);
  a63=(a29*a10);
  a62=(a62+a63);
  a63=(a34*a12);
  a62=(a62+a63);
  a61=(a61+a62);
  a62=(a22*a13);
  a63=(a29*a14);
  a62=(a62+a63);
  a63=(a34*a15);
  a62=(a62+a63);
  a61=(a61-a62);
  a61=(a59*a61);
  a50=(a50-a61);
  a31=(a31-a50);
  if (res[0]!=0) res[0][24]=a31;
  a31=(a21*a19);
  a50=(a28*a20);
  a31=(a31+a50);
  a50=(a33*a27);
  a31=(a31+a50);
  a50=(a40*a37);
  a31=(a31+a50);
  a50=(a43*a38);
  a31=(a31+a50);
  a50=(a46*a41);
  a31=(a31+a50);
  a50=(a21*a30);
  a31=(a31-a50);
  a50=(a28*a49);
  a31=(a31-a50);
  a50=(a33*a26);
  a31=(a31-a50);
  a50=(a1-a6);
  a61=(a50-a16);
  a62=(a61*a6);
  a63=(a2-a10);
  a64=(a63-a17);
  a65=(a64*a10);
  a62=(a62+a65);
  a65=(a3-a12);
  a66=(a65-a18);
  a67=(a66*a12);
  a62=(a62+a67);
  a67=(a61*a1);
  a68=(a64*a2);
  a67=(a67+a68);
  a68=(a66*a3);
  a67=(a67+a68);
  a68=(a21*a9);
  a69=(a28*a8);
  a68=(a68+a69);
  a69=(a33*a5);
  a68=(a68+a69);
  a69=(a35*a68);
  a67=(a67+a69);
  a62=(a62-a67);
  a67=(a61*a16);
  a69=(a64*a17);
  a67=(a67+a69);
  a69=(a66*a18);
  a67=(a67+a69);
  a62=(a62+a67);
  a67=casadi_sq(a21);
  a69=casadi_sq(a28);
  a67=(a67+a69);
  a69=casadi_sq(a33);
  a67=(a67+a69);
  a67=(a67-a60);
  a67=(a58*a67);
  a67=(a53*a67);
  a62=(a62-a67);
  a67=(a21*a1);
  a69=(a28*a2);
  a67=(a67+a69);
  a69=(a33*a3);
  a67=(a67+a69);
  a69=(a21*a6);
  a70=(a28*a10);
  a69=(a69+a70);
  a70=(a33*a12);
  a69=(a69+a70);
  a67=(a67-a69);
  a69=(a21*a16);
  a70=(a28*a17);
  a69=(a69+a70);
  a70=(a33*a18);
  a69=(a69+a70);
  a67=(a67-a69);
  a67=(a59*a67);
  a62=(a62-a67);
  a31=(a31-a62);
  if (res[0]!=0) res[0][25]=a31;
  a31=(a23+a25);
  if (res[1]!=0) res[1][0]=a31;
  a62=(a23*a5);
  a67=(a25*a5);
  a69=(a62-a67);
  if (res[1]!=0) res[1][1]=a69;
  a69=(a25*a8);
  a70=(a23*a8);
  a71=(a69-a70);
  if (res[1]!=0) res[1][2]=a71;
  a71=(-a23);
  if (res[1]!=0) res[1][3]=a71;
  a72=(-a25);
  if (res[1]!=0) res[1][4]=a72;
  a73=(a38*a5);
  a74=(a19+a73);
  a75=(a41*a8);
  a76=(a74-a75);
  a76=(a76-a47);
  a77=(a35*a9);
  a78=(a22+a22);
  a78=(a58*a78);
  a78=(a53*a78);
  a79=(a77-a78);
  a80=(a59*a52);
  a79=(a79-a80);
  a76=(a76-a79);
  if (res[1]!=0) res[1][5]=a76;
  a76=(a19-a73);
  a76=(a76+a75);
  a76=(a76-a30);
  a79=(a21+a21);
  a79=(a58*a79);
  a79=(a53*a79);
  a80=(a77+a79);
  a81=(a59*a61);
  a81=(a80+a81);
  a76=(a76+a81);
  if (res[1]!=0) res[1][6]=a76;
  if (res[1]!=0) res[1][7]=a31;
  a76=(a67-a62);
  if (res[1]!=0) res[1][8]=a76;
  a76=(a23*a9);
  a81=(a25*a9);
  a82=(a76-a81);
  if (res[1]!=0) res[1][9]=a82;
  if (res[1]!=0) res[1][10]=a71;
  if (res[1]!=0) res[1][11]=a72;
  a82=(a37*a5);
  a83=(a20-a82);
  a84=(a41*a9);
  a83=(a83+a84);
  a83=(a83-a48);
  a85=(a35*a8);
  a86=(a29+a29);
  a86=(a58*a86);
  a86=(a53*a86);
  a87=(a85-a86);
  a88=(a59*a55);
  a87=(a87-a88);
  a83=(a83-a87);
  if (res[1]!=0) res[1][12]=a83;
  a83=(a20+a82);
  a87=(a83-a84);
  a87=(a87-a49);
  a88=(a28+a28);
  a88=(a58*a88);
  a88=(a53*a88);
  a89=(a85+a88);
  a90=(a59*a64);
  a90=(a89+a90);
  a87=(a87+a90);
  if (res[1]!=0) res[1][13]=a87;
  if (res[1]!=0) res[1][14]=a31;
  a31=(a70-a69);
  if (res[1]!=0) res[1][15]=a31;
  a31=(a81-a76);
  if (res[1]!=0) res[1][16]=a31;
  if (res[1]!=0) res[1][17]=a71;
  if (res[1]!=0) res[1][18]=a72;
  a31=(a37*a8);
  a87=(a27+a31);
  a90=(a38*a9);
  a91=(a87-a90);
  a91=(a91-a24);
  a92=(a35*a5);
  a93=(a34+a34);
  a93=(a58*a93);
  a93=(a53*a93);
  a94=(a92-a93);
  a95=(a59*a57);
  a94=(a94-a95);
  a91=(a91-a94);
  if (res[1]!=0) res[1][19]=a91;
  a91=(a27-a31);
  a91=(a91+a90);
  a91=(a91-a26);
  a94=(a33+a33);
  a58=(a58*a94);
  a53=(a53*a58);
  a58=(a92+a53);
  a94=(a59*a66);
  a94=(a58+a94);
  a91=(a91+a94);
  if (res[1]!=0) res[1][20]=a91;
  a91=(-a7);
  if (res[1]!=0) res[1][21]=a91;
  if (res[1]!=0) res[1][22]=a4;
  a91=(a23-a25);
  if (res[1]!=0) res[1][23]=a91;
  a94=(a5-a34);
  a95=(a23*a94);
  a96=(a33+a5);
  a97=(a25*a96);
  a95=(a95+a97);
  if (res[1]!=0) res[1][24]=a95;
  a95=(a29-a8);
  a97=(a23*a95);
  a98=(a8+a28);
  a99=(a25*a98);
  a97=(a97-a99);
  if (res[1]!=0) res[1][25]=a97;
  if (res[1]!=0) res[1][26]=a71;
  if (res[1]!=0) res[1][27]=a25;
  a94=(a38*a94);
  a94=(a19+a94);
  a95=(a41*a95);
  a94=(a94+a95);
  a94=(a94-a47);
  a95=(a9+a22);
  a95=(a35*a95);
  a97=(a2*a7);
  a99=(a3*a4);
  a100=(a97-a99);
  a95=(a95-a100);
  a100=(a10*a7);
  a101=(a55*a7);
  a101=(a100+a101);
  a102=(a12*a4);
  a103=(a57*a4);
  a103=(a102+a103);
  a101=(a101-a103);
  a95=(a95-a101);
  a101=(a14*a7);
  a103=(a15*a4);
  a101=(a101-a103);
  a95=(a95+a101);
  a95=(a95-a78);
  a101=(a29*a7);
  a101=(a6+a101);
  a103=(a34*a4);
  a101=(a101-a103);
  a101=(a1+a101);
  a101=(a101-a13);
  a101=(a59*a101);
  a95=(a95-a101);
  a94=(a94-a95);
  if (res[1]!=0) res[1][28]=a94;
  a96=(a38*a96);
  a96=(a96-a19);
  a98=(a41*a98);
  a96=(a96-a98);
  a96=(a96+a30);
  a98=(a64*a7);
  a98=(a98-a100);
  a100=(a66*a4);
  a102=(a102-a100);
  a98=(a98+a102);
  a99=(a99-a97);
  a97=(a21-a9);
  a97=(a35*a97);
  a99=(a99+a97);
  a98=(a98-a99);
  a99=(a18*a4);
  a97=(a17*a7);
  a99=(a99-a97);
  a98=(a98+a99);
  a98=(a98+a79);
  a79=(a28*a7);
  a79=(a79-a6);
  a99=(a33*a4);
  a79=(a79-a99);
  a79=(a1+a79);
  a79=(a16-a79);
  a79=(a59*a79);
  a98=(a98-a79);
  a96=(a96-a98);
  if (res[1]!=0) res[1][29]=a96;
  if (res[1]!=0) res[1][30]=a7;
  a96=(-a11);
  if (res[1]!=0) res[1][31]=a96;
  if (res[1]!=0) res[1][32]=a91;
  a96=(a34-a5);
  a98=(a23*a96);
  a79=(a5+a33);
  a99=(a25*a79);
  a98=(a98-a99);
  if (res[1]!=0) res[1][33]=a98;
  a98=(a9-a22);
  a99=(a23*a98);
  a97=(a21+a9);
  a102=(a25*a97);
  a99=(a99+a102);
  if (res[1]!=0) res[1][34]=a99;
  if (res[1]!=0) res[1][35]=a71;
  if (res[1]!=0) res[1][36]=a25;
  a96=(a37*a96);
  a96=(a20+a96);
  a98=(a41*a98);
  a96=(a96+a98);
  a96=(a96-a48);
  a98=(a8+a29);
  a98=(a35*a98);
  a99=(a3*a11);
  a102=(a1*a7);
  a100=(a99-a102);
  a98=(a98-a100);
  a100=(a12*a11);
  a94=(a57*a11);
  a94=(a100+a94);
  a95=(a6*a7);
  a101=(a52*a7);
  a101=(a95+a101);
  a94=(a94-a101);
  a98=(a98-a94);
  a94=(a15*a11);
  a101=(a13*a7);
  a94=(a94-a101);
  a98=(a98+a94);
  a98=(a98-a86);
  a94=(a22*a7);
  a94=(a10-a94);
  a101=(a34*a11);
  a94=(a94+a101);
  a94=(a2+a94);
  a94=(a94-a14);
  a94=(a59*a94);
  a98=(a98-a94);
  a96=(a96-a98);
  if (res[1]!=0) res[1][37]=a96;
  a41=(a41*a97);
  a79=(a37*a79);
  a79=(a20+a79);
  a41=(a41-a79);
  a41=(a41+a49);
  a79=(a61*a7);
  a95=(a95-a79);
  a79=(a66*a11);
  a79=(a79-a100);
  a95=(a95+a79);
  a102=(a102-a99);
  a99=(a28-a8);
  a99=(a35*a99);
  a102=(a102+a99);
  a95=(a95-a102);
  a102=(a16*a7);
  a99=(a18*a11);
  a102=(a102-a99);
  a95=(a95+a102);
  a95=(a95+a88);
  a88=(a33*a11);
  a102=(a21*a7);
  a102=(a102+a10);
  a88=(a88-a102);
  a88=(a2+a88);
  a88=(a17-a88);
  a88=(a59*a88);
  a95=(a95-a88);
  a41=(a41-a95);
  if (res[1]!=0) res[1][38]=a41;
  a41=(-a4);
  if (res[1]!=0) res[1][39]=a41;
  if (res[1]!=0) res[1][40]=a11;
  if (res[1]!=0) res[1][41]=a91;
  a91=(a8-a29);
  a41=(a23*a91);
  a95=(a28+a8);
  a88=(a25*a95);
  a41=(a41+a88);
  if (res[1]!=0) res[1][42]=a41;
  a41=(a22-a9);
  a88=(a23*a41);
  a102=(a9+a21);
  a99=(a25*a102);
  a88=(a88-a99);
  if (res[1]!=0) res[1][43]=a88;
  if (res[1]!=0) res[1][44]=a71;
  if (res[1]!=0) res[1][45]=a25;
  a91=(a37*a91);
  a91=(a27+a91);
  a41=(a38*a41);
  a91=(a91+a41);
  a91=(a91-a24);
  a41=(a5+a34);
  a41=(a35*a41);
  a88=(a1*a4);
  a99=(a2*a11);
  a79=(a88-a99);
  a41=(a41-a79);
  a79=(a6*a4);
  a100=(a52*a4);
  a100=(a79+a100);
  a97=(a10*a11);
  a96=(a55*a11);
  a96=(a97+a96);
  a100=(a100-a96);
  a41=(a41-a100);
  a100=(a13*a4);
  a96=(a14*a11);
  a100=(a100-a96);
  a41=(a41+a100);
  a41=(a41-a93);
  a100=(a22*a4);
  a96=(a29*a11);
  a100=(a100-a96);
  a100=(a100+a12);
  a100=(a3+a100);
  a100=(a100-a15);
  a100=(a59*a100);
  a41=(a41-a100);
  a91=(a91-a41);
  if (res[1]!=0) res[1][46]=a91;
  a37=(a37*a95);
  a37=(a37-a27);
  a38=(a38*a102);
  a37=(a37-a38);
  a37=(a37+a26);
  a38=(a61*a4);
  a38=(a38-a79);
  a79=(a64*a11);
  a97=(a97-a79);
  a38=(a38+a97);
  a99=(a99-a88);
  a88=(a33-a5);
  a35=(a35*a88);
  a99=(a99+a35);
  a38=(a38-a99);
  a99=(a17*a11);
  a35=(a16*a4);
  a99=(a99-a35);
  a38=(a38+a99);
  a38=(a38+a53);
  a53=(a21*a4);
  a99=(a28*a11);
  a53=(a53-a99);
  a53=(a53-a12);
  a53=(a3+a53);
  a53=(a18-a53);
  a53=(a59*a53);
  a38=(a38-a53);
  a37=(a37-a38);
  if (res[1]!=0) res[1][47]=a37;
  if (res[1]!=0) res[1][48]=a71;
  a37=(-a62);
  if (res[1]!=0) res[1][49]=a37;
  if (res[1]!=0) res[1][50]=a70;
  if (res[1]!=0) res[1][51]=a23;
  a74=(a75-a74);
  a74=(a74+a47);
  a78=(a78-a77);
  a77=(a13-a51);
  a77=(a59*a77);
  a78=(a78-a77);
  a74=(a74-a78);
  if (res[1]!=0) res[1][52]=a74;
  if (res[1]!=0) res[1][53]=a71;
  if (res[1]!=0) res[1][54]=a62;
  a62=(-a76);
  if (res[1]!=0) res[1][55]=a62;
  if (res[1]!=0) res[1][56]=a23;
  a82=(a82-a20);
  a82=(a82-a84);
  a82=(a82+a48);
  a86=(a86-a85);
  a85=(a14-a54);
  a85=(a59*a85);
  a86=(a86-a85);
  a82=(a82-a86);
  if (res[1]!=0) res[1][57]=a82;
  if (res[1]!=0) res[1][58]=a71;
  a70=(-a70);
  if (res[1]!=0) res[1][59]=a70;
  if (res[1]!=0) res[1][60]=a76;
  if (res[1]!=0) res[1][61]=a23;
  a87=(a90-a87);
  a87=(a87+a24);
  a93=(a93-a92);
  a92=(a15-a56);
  a92=(a59*a92);
  a93=(a93-a92);
  a87=(a87-a93);
  if (res[1]!=0) res[1][62]=a87;
  if (res[1]!=0) res[1][63]=a72;
  if (res[1]!=0) res[1][64]=a67;
  a87=(-a69);
  if (res[1]!=0) res[1][65]=a87;
  if (res[1]!=0) res[1][66]=a25;
  a73=(a73-a19);
  a73=(a73-a75);
  a73=(a73+a30);
  a30=(a6-a1);
  a30=(a30+a16);
  a30=(a59*a30);
  a80=(a80-a30);
  a73=(a73-a80);
  if (res[1]!=0) res[1][67]=a73;
  if (res[1]!=0) res[1][68]=a72;
  a67=(-a67);
  if (res[1]!=0) res[1][69]=a67;
  if (res[1]!=0) res[1][70]=a81;
  if (res[1]!=0) res[1][71]=a25;
  a84=(a84-a83);
  a84=(a84+a49);
  a49=(a10-a2);
  a49=(a49+a17);
  a49=(a59*a49);
  a89=(a89-a49);
  a84=(a84-a89);
  if (res[1]!=0) res[1][72]=a84;
  if (res[1]!=0) res[1][73]=a72;
  if (res[1]!=0) res[1][74]=a69;
  a81=(-a81);
  if (res[1]!=0) res[1][75]=a81;
  if (res[1]!=0) res[1][76]=a25;
  a31=(a31-a27);
  a31=(a31-a90);
  a31=(a31+a26);
  a26=(a12-a3);
  a26=(a26+a18);
  a26=(a59*a26);
  a58=(a58-a26);
  a31=(a31-a58);
  if (res[1]!=0) res[1][77]=a31;
  a31=-1.;
  if (res[1]!=0) res[1][78]=a31;
  a58=(a1+a52);
  a58=(a58+a6);
  a58=(a13-a58);
  a26=(a59*a22);
  a58=(a58-a26);
  a58=(-a58);
  if (res[1]!=0) res[1][79]=a58;
  a58=(a1+a61);
  a58=(a6-a58);
  a58=(a58+a16);
  a90=(a59*a21);
  a58=(a58-a90);
  a58=(-a58);
  if (res[1]!=0) res[1][80]=a58;
  if (res[1]!=0) res[1][81]=a31;
  a58=(a2+a55);
  a58=(a58+a10);
  a58=(a14-a58);
  a27=(a59*a29);
  a58=(a58-a27);
  a58=(-a58);
  if (res[1]!=0) res[1][82]=a58;
  a58=(a2+a64);
  a58=(a10-a58);
  a58=(a58+a17);
  a25=(a59*a28);
  a58=(a58-a25);
  a58=(-a58);
  if (res[1]!=0) res[1][83]=a58;
  if (res[1]!=0) res[1][84]=a31;
  a58=(a3+a57);
  a58=(a58+a12);
  a58=(a15-a58);
  a81=(a59*a34);
  a58=(a58-a81);
  a58=(-a58);
  if (res[1]!=0) res[1][85]=a58;
  a58=(a3+a66);
  a58=(a12-a58);
  a58=(a58+a18);
  a69=(a59*a33);
  a58=(a58-a69);
  a58=(-a58);
  if (res[1]!=0) res[1][86]=a58;
  if (res[1]!=0) res[1][87]=a5;
  a58=(-a8);
  if (res[1]!=0) res[1][88]=a58;
  a11=(a11+a11);
  a58=(a36*a11);
  a72=(a3*a8);
  a84=(a2*a5);
  a89=(a72-a84);
  a58=(a58-a89);
  a89=(a12*a8);
  a49=(a57*a8);
  a49=(a89+a49);
  a83=(a10*a5);
  a67=(a55*a5);
  a67=(a83+a67);
  a49=(a49-a67);
  a58=(a58-a49);
  a49=(a15*a8);
  a67=(a14*a5);
  a49=(a49-a67);
  a58=(a58+a49);
  a49=(a34*a8);
  a67=(a29*a5);
  a49=(a49-a67);
  a49=(a59*a49);
  a58=(a58-a49);
  a58=(-a58);
  if (res[1]!=0) res[1][89]=a58;
  a58=(a64*a5);
  a83=(a83-a58);
  a58=(a66*a8);
  a58=(a58-a89);
  a83=(a83+a58);
  a84=(a84-a72);
  a11=(a68*a11);
  a84=(a84+a11);
  a83=(a83-a84);
  a84=(a17*a5);
  a11=(a18*a8);
  a84=(a84-a11);
  a83=(a83+a84);
  a84=(a33*a8);
  a11=(a28*a5);
  a84=(a84-a11);
  a84=(a59*a84);
  a83=(a83+a84);
  a83=(-a83);
  if (res[1]!=0) res[1][90]=a83;
  a83=(-a5);
  if (res[1]!=0) res[1][91]=a83;
  if (res[1]!=0) res[1][92]=a9;
  a4=(a4+a4);
  a83=(a36*a4);
  a84=(a1*a5);
  a3=(a3*a9);
  a11=(a84-a3);
  a83=(a83-a11);
  a11=(a6*a5);
  a72=(a52*a5);
  a72=(a11+a72);
  a12=(a12*a9);
  a58=(a57*a9);
  a58=(a12+a58);
  a72=(a72-a58);
  a83=(a83-a72);
  a72=(a13*a5);
  a58=(a15*a9);
  a72=(a72-a58);
  a83=(a83+a72);
  a72=(a22*a5);
  a58=(a34*a9);
  a72=(a72-a58);
  a72=(a59*a72);
  a83=(a83-a72);
  a83=(-a83);
  if (res[1]!=0) res[1][93]=a83;
  a83=(a61*a5);
  a83=(a83-a11);
  a11=(a66*a9);
  a12=(a12-a11);
  a83=(a83+a12);
  a3=(a3-a84);
  a4=(a68*a4);
  a3=(a3+a4);
  a83=(a83-a3);
  a3=(a18*a9);
  a4=(a16*a5);
  a3=(a3-a4);
  a83=(a83+a3);
  a5=(a21*a5);
  a3=(a33*a9);
  a5=(a5-a3);
  a5=(a59*a5);
  a83=(a83+a5);
  a83=(-a83);
  if (res[1]!=0) res[1][94]=a83;
  if (res[1]!=0) res[1][95]=a8;
  a83=(-a9);
  if (res[1]!=0) res[1][96]=a83;
  a7=(a7+a7);
  a36=(a36*a7);
  a2=(a2*a9);
  a1=(a1*a8);
  a83=(a2-a1);
  a36=(a36-a83);
  a10=(a10*a9);
  a83=(a55*a9);
  a83=(a10+a83);
  a6=(a6*a8);
  a5=(a52*a8);
  a5=(a6+a5);
  a83=(a83-a5);
  a36=(a36-a83);
  a83=(a14*a9);
  a5=(a13*a8);
  a83=(a83-a5);
  a36=(a36+a83);
  a83=(a29*a9);
  a5=(a22*a8);
  a83=(a83-a5);
  a83=(a59*a83);
  a36=(a36-a83);
  a36=(-a36);
  if (res[1]!=0) res[1][97]=a36;
  a36=(a61*a8);
  a6=(a6-a36);
  a36=(a64*a9);
  a36=(a36-a10);
  a6=(a6+a36);
  a1=(a1-a2);
  a68=(a68*a7);
  a1=(a1+a68);
  a6=(a6-a1);
  a1=(a16*a8);
  a68=(a17*a9);
  a1=(a1-a68);
  a6=(a6+a1);
  a9=(a28*a9);
  a8=(a21*a8);
  a9=(a9-a8);
  a59=(a59*a9);
  a6=(a6+a59);
  a6=(-a6);
  if (res[1]!=0) res[1][98]=a6;
  if (res[1]!=0) res[1][99]=a31;
  a52=(a52-a13);
  a51=(a51+a52);
  a51=(a51+a26);
  a51=(-a51);
  if (res[1]!=0) res[1][100]=a51;
  if (res[1]!=0) res[1][101]=a31;
  a55=(a55-a14);
  a54=(a54+a55);
  a54=(a54+a27);
  a54=(-a54);
  if (res[1]!=0) res[1][102]=a54;
  if (res[1]!=0) res[1][103]=a31;
  a57=(a57-a15);
  a56=(a56+a57);
  a56=(a56+a81);
  a56=(-a56);
  if (res[1]!=0) res[1][104]=a56;
  if (res[1]!=0) res[1][105]=a31;
  a61=(a61-a16);
  a50=(a50+a61);
  a50=(a50+a90);
  a50=(-a50);
  if (res[1]!=0) res[1][106]=a50;
  if (res[1]!=0) res[1][107]=a31;
  a64=(a64-a17);
  a63=(a63+a64);
  a63=(a63+a25);
  a63=(-a63);
  if (res[1]!=0) res[1][108]=a63;
  if (res[1]!=0) res[1][109]=a31;
  a66=(a66-a18);
  a65=(a65+a66);
  a65=(a65+a69);
  a65=(-a65);
  if (res[1]!=0) res[1][110]=a65;
  if (res[2]!=0) res[2][0]=a60;
  if (res[2]!=0) res[2][1]=a60;
  if (res[2]!=0) res[2][2]=a60;
  if (res[2]!=0) res[2][3]=a60;
  if (res[2]!=0) res[2][4]=a60;
  if (res[2]!=0) res[2][5]=a60;
  if (res[2]!=0) res[2][6]=a60;
  if (res[2]!=0) res[2][7]=a60;
  if (res[2]!=0) res[2][8]=a60;
  if (res[2]!=0) res[2][9]=a60;
  if (res[2]!=0) res[2][10]=a60;
  if (res[2]!=0) res[2][11]=a60;
  if (res[2]!=0) res[2][12]=a0;
  if (res[2]!=0) res[2][13]=a22;
  if (res[2]!=0) res[2][14]=a21;
  if (res[2]!=0) res[2][15]=a0;
  if (res[2]!=0) res[2][16]=a29;
  if (res[2]!=0) res[2][17]=a28;
  if (res[2]!=0) res[2][18]=a0;
  if (res[2]!=0) res[2][19]=a34;
  if (res[2]!=0) res[2][20]=a33;
  if (res[2]!=0) res[2][21]=a32;
  if (res[2]!=0) res[2][22]=a39;
  if (res[2]!=0) res[2][23]=a40;
  if (res[2]!=0) res[2][24]=a32;
  if (res[2]!=0) res[2][25]=a42;
  if (res[2]!=0) res[2][26]=a43;
  if (res[2]!=0) res[2][27]=a32;
  if (res[2]!=0) res[2][28]=a45;
  if (res[2]!=0) res[2][29]=a46;
  if (res[2]!=0) res[2][30]=a44;
  a22=(-a22);
  if (res[2]!=0) res[2][31]=a22;
  if (res[2]!=0) res[2][32]=a44;
  a29=(-a29);
  if (res[2]!=0) res[2][33]=a29;
  if (res[2]!=0) res[2][34]=a44;
  a34=(-a34);
  if (res[2]!=0) res[2][35]=a34;
  if (res[2]!=0) res[2][36]=a44;
  a21=(-a21);
  if (res[2]!=0) res[2][37]=a21;
  if (res[2]!=0) res[2][38]=a44;
  a28=(-a28);
  if (res[2]!=0) res[2][39]=a28;
  if (res[2]!=0) res[2][40]=a44;
  a33=(-a33);
  if (res[2]!=0) res[2][41]=a33;
  if (res[3]!=0) res[3][0]=a31;
  if (res[3]!=0) res[3][1]=a31;
  if (res[3]!=0) res[3][2]=a31;
  if (res[3]!=0) res[3][3]=a31;
  if (res[3]!=0) res[3][4]=a31;
  if (res[3]!=0) res[3][5]=a31;
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dae_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dae_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dae_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void dae_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dae_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int dae_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real dae_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dae_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dae_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dae_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dae_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
