// Generated by gencpp from file quadrotor_msgs/mpc_ref_traj.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_MPC_REF_TRAJ_H
#define QUADROTOR_MSGS_MESSAGE_MPC_REF_TRAJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <quadrotor_msgs/mpc_ref_point.h>
#include <geometry_msgs/Vector3.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct mpc_ref_traj_
{
  typedef mpc_ref_traj_<ContainerAllocator> Type;

  mpc_ref_traj_()
    : header()
    , mpc_ref_points()
    , goal()  {
    }
  mpc_ref_traj_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mpc_ref_points(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::quadrotor_msgs::mpc_ref_point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::quadrotor_msgs::mpc_ref_point_<ContainerAllocator> >> _mpc_ref_points_type;
  _mpc_ref_points_type mpc_ref_points;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> const> ConstPtr;

}; // struct mpc_ref_traj_

typedef ::quadrotor_msgs::mpc_ref_traj_<std::allocator<void> > mpc_ref_traj;

typedef boost::shared_ptr< ::quadrotor_msgs::mpc_ref_traj > mpc_ref_trajPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::mpc_ref_traj const> mpc_ref_trajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mpc_ref_points == rhs.mpc_ref_points &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4faae5b6cb706021d9657ec34fedc421";
  }

  static const char* value(const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4faae5b6cb706021ULL;
  static const uint64_t static_value2 = 0xd9657ec34fedc421ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/mpc_ref_traj";
  }

  static const char* value(const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"mpc_ref_point[] mpc_ref_points\n"
"geometry_msgs/Vector3 goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: quadrotor_msgs/mpc_ref_point\n"
"Header header\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mpc_ref_points);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mpc_ref_traj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::mpc_ref_traj_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mpc_ref_points[]" << std::endl;
    for (size_t i = 0; i < v.mpc_ref_points.size(); ++i)
    {
      s << indent << "  mpc_ref_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::quadrotor_msgs::mpc_ref_point_<ContainerAllocator> >::stream(s, indent + "    ", v.mpc_ref_points[i]);
    }
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_MPC_REF_TRAJ_H
