/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) NMPC_model_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

/* NMPC_model_cost_ext_cost_fun_jac:(i0[6],i1[3],i2[],i3[18])->(o0,o1[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a0=(a0-a1);
  a1=arg[3]? arg[3][9] : 0;
  a2=(a0*a1);
  a3=(a2*a0);
  a4=arg[0]? arg[0][1] : 0;
  a5=arg[3]? arg[3][1] : 0;
  a4=(a4-a5);
  a5=arg[3]? arg[3][10] : 0;
  a6=(a4*a5);
  a7=(a6*a4);
  a3=(a3+a7);
  a7=arg[0]? arg[0][2] : 0;
  a8=arg[3]? arg[3][2] : 0;
  a7=(a7-a8);
  a8=arg[3]? arg[3][11] : 0;
  a9=(a7*a8);
  a10=(a9*a7);
  a3=(a3+a10);
  a10=arg[0]? arg[0][3] : 0;
  a11=arg[3]? arg[3][3] : 0;
  a10=(a10-a11);
  a11=arg[3]? arg[3][12] : 0;
  a12=(a10*a11);
  a13=(a12*a10);
  a3=(a3+a13);
  a13=arg[0]? arg[0][4] : 0;
  a14=arg[3]? arg[3][4] : 0;
  a13=(a13-a14);
  a14=arg[3]? arg[3][13] : 0;
  a15=(a13*a14);
  a16=(a15*a13);
  a3=(a3+a16);
  a16=arg[0]? arg[0][5] : 0;
  a17=arg[3]? arg[3][5] : 0;
  a16=(a16-a17);
  a17=arg[3]? arg[3][14] : 0;
  a18=(a16*a17);
  a19=(a18*a16);
  a3=(a3+a19);
  a19=arg[1]? arg[1][0] : 0;
  a20=arg[3]? arg[3][6] : 0;
  a19=(a19-a20);
  a20=arg[3]? arg[3][15] : 0;
  a21=(a19*a20);
  a22=(a21*a19);
  a3=(a3+a22);
  a22=arg[1]? arg[1][1] : 0;
  a23=arg[3]? arg[3][7] : 0;
  a22=(a22-a23);
  a23=arg[3]? arg[3][16] : 0;
  a24=(a22*a23);
  a25=(a24*a22);
  a3=(a3+a25);
  a25=arg[1]? arg[1][2] : 0;
  a26=arg[3]? arg[3][8] : 0;
  a25=(a25-a26);
  a26=arg[3]? arg[3][17] : 0;
  a27=(a25*a26);
  a28=(a27*a25);
  a3=(a3+a28);
  if (res[0]!=0) res[0][0]=a3;
  a20=(a20*a19);
  a21=(a21+a20);
  if (res[1]!=0) res[1][0]=a21;
  a23=(a23*a22);
  a24=(a24+a23);
  if (res[1]!=0) res[1][1]=a24;
  a26=(a26*a25);
  a27=(a27+a26);
  if (res[1]!=0) res[1][2]=a27;
  a1=(a1*a0);
  a2=(a2+a1);
  if (res[1]!=0) res[1][3]=a2;
  a5=(a5*a4);
  a6=(a6+a5);
  if (res[1]!=0) res[1][4]=a6;
  a8=(a8*a7);
  a9=(a9+a8);
  if (res[1]!=0) res[1][5]=a9;
  a11=(a11*a10);
  a12=(a12+a11);
  if (res[1]!=0) res[1][6]=a12;
  a14=(a14*a13);
  a15=(a15+a14);
  if (res[1]!=0) res[1][7]=a15;
  a17=(a17*a16);
  a18=(a18+a17);
  if (res[1]!=0) res[1][8]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void NMPC_model_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void NMPC_model_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void NMPC_model_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void NMPC_model_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int NMPC_model_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int NMPC_model_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real NMPC_model_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* NMPC_model_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* NMPC_model_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* NMPC_model_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* NMPC_model_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
