/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dae_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[72] = {30, 6, 0, 3, 9, 18, 27, 45, 63, 9, 10, 11, 9, 10, 11, 21, 22, 23, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 15, 16, 17, 6, 7, 8, 9, 10, 11, 12, 13, 14, 18, 19, 20, 21, 22, 23, 24, 25, 26, 6, 7, 8, 9, 10, 11, 15, 16, 17, 18, 19, 20, 21, 22, 23, 27, 28, 29};
static const casadi_int casadi_s5[5] = {6, 2, 0, 0, 0};

/* dae_constr_h_fun_jac_uxt_zt:(i0[24],i1[6],i2[2],i3[])->(o0[6],o1[30x6,63nz],o2[6x2,0nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=1.;
  a1=arg[0]? arg[0][3] : 0;
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][4] : 0;
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=arg[0]? arg[0][5] : 0;
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a2=(a0-a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0]? arg[0][15] : 0;
  a5=(a1*a2);
  a6=arg[0]? arg[0][16] : 0;
  a7=(a3*a6);
  a5=(a5+a7);
  a7=arg[0]? arg[0][17] : 0;
  a8=(a4*a7);
  a5=(a5+a8);
  if (res[0]!=0) res[0][1]=a5;
  a5=5.0000000000000000e-01;
  a8=arg[0]? arg[0][0] : 0;
  a9=(a8+a1);
  a10=arg[0]? arg[0][6] : 0;
  a9=(a9-a10);
  a10=casadi_sq(a9);
  a11=arg[0]? arg[0][1] : 0;
  a12=(a11+a3);
  a13=arg[0]? arg[0][7] : 0;
  a12=(a12-a13);
  a13=casadi_sq(a12);
  a10=(a10+a13);
  a13=arg[0]? arg[0][2] : 0;
  a14=(a13+a4);
  a15=arg[0]? arg[0][8] : 0;
  a14=(a14-a15);
  a15=casadi_sq(a14);
  a10=(a10+a15);
  a10=(a10-a0);
  a10=(a5*a10);
  if (res[0]!=0) res[0][2]=a10;
  a8=(a8-a1);
  a10=arg[0]? arg[0][9] : 0;
  a8=(a8-a10);
  a10=casadi_sq(a8);
  a11=(a11-a3);
  a15=arg[0]? arg[0][10] : 0;
  a11=(a11-a15);
  a15=casadi_sq(a11);
  a10=(a10+a15);
  a13=(a13-a4);
  a15=arg[0]? arg[0][11] : 0;
  a13=(a13-a15);
  a15=casadi_sq(a13);
  a10=(a10+a15);
  a10=(a10-a0);
  a10=(a5*a10);
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[0]? arg[0][12] : 0;
  a0=(a9*a10);
  a15=arg[0]? arg[0][13] : 0;
  a16=(a12*a15);
  a0=(a0+a16);
  a16=arg[0]? arg[0][14] : 0;
  a17=(a14*a16);
  a0=(a0+a17);
  a17=(a6*a4);
  a18=(a7*a3);
  a17=(a17-a18);
  a18=(a9*a17);
  a19=(a7*a1);
  a20=(a2*a4);
  a19=(a19-a20);
  a20=(a12*a19);
  a18=(a18+a20);
  a20=(a2*a3);
  a21=(a6*a1);
  a20=(a20-a21);
  a21=(a14*a20);
  a18=(a18+a21);
  a0=(a0+a18);
  a18=arg[0]? arg[0][18] : 0;
  a21=(a9*a18);
  a22=arg[0]? arg[0][19] : 0;
  a23=(a12*a22);
  a21=(a21+a23);
  a23=arg[0]? arg[0][20] : 0;
  a24=(a14*a23);
  a21=(a21+a24);
  a0=(a0-a21);
  if (res[0]!=0) res[0][4]=a0;
  a0=(a8*a10);
  a21=(a11*a15);
  a0=(a0+a21);
  a21=(a13*a16);
  a0=(a0+a21);
  a21=(a8*a17);
  a24=(a11*a19);
  a21=(a21+a24);
  a24=(a13*a20);
  a21=(a21+a24);
  a0=(a0-a21);
  a21=arg[0]? arg[0][21] : 0;
  a24=(a8*a21);
  a25=arg[0]? arg[0][22] : 0;
  a26=(a11*a25);
  a24=(a24+a26);
  a26=arg[0]? arg[0][23] : 0;
  a27=(a13*a26);
  a24=(a24+a27);
  a0=(a0-a24);
  if (res[0]!=0) res[0][5]=a0;
  a0=(a1+a1);
  a0=(-a0);
  if (res[1]!=0) res[1][0]=a0;
  a0=(a3+a3);
  a0=(-a0);
  if (res[1]!=0) res[1][1]=a0;
  a0=(a4+a4);
  a0=(-a0);
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a2;
  if (res[1]!=0) res[1][4]=a6;
  if (res[1]!=0) res[1][5]=a7;
  if (res[1]!=0) res[1][6]=a1;
  if (res[1]!=0) res[1][7]=a3;
  if (res[1]!=0) res[1][8]=a4;
  a0=(a9+a9);
  a0=(a5*a0);
  if (res[1]!=0) res[1][9]=a0;
  a24=(a12+a12);
  a24=(a5*a24);
  if (res[1]!=0) res[1][10]=a24;
  a27=(a14+a14);
  a27=(a5*a27);
  if (res[1]!=0) res[1][11]=a27;
  if (res[1]!=0) res[1][12]=a0;
  if (res[1]!=0) res[1][13]=a24;
  if (res[1]!=0) res[1][14]=a27;
  a0=(-a0);
  if (res[1]!=0) res[1][15]=a0;
  a24=(-a24);
  if (res[1]!=0) res[1][16]=a24;
  a27=(-a27);
  if (res[1]!=0) res[1][17]=a27;
  a27=(a8+a8);
  a27=(a5*a27);
  if (res[1]!=0) res[1][18]=a27;
  a24=(a11+a11);
  a24=(a5*a24);
  if (res[1]!=0) res[1][19]=a24;
  a0=(a13+a13);
  a5=(a5*a0);
  if (res[1]!=0) res[1][20]=a5;
  a27=(-a27);
  if (res[1]!=0) res[1][21]=a27;
  a24=(-a24);
  if (res[1]!=0) res[1][22]=a24;
  a5=(-a5);
  if (res[1]!=0) res[1][23]=a5;
  if (res[1]!=0) res[1][24]=a27;
  if (res[1]!=0) res[1][25]=a24;
  if (res[1]!=0) res[1][26]=a5;
  a5=(a17-a18);
  a5=(a5+a10);
  if (res[1]!=0) res[1][27]=a5;
  a5=(a19-a22);
  a5=(a5+a15);
  if (res[1]!=0) res[1][28]=a5;
  a5=(a20-a23);
  a24=(a5+a16);
  if (res[1]!=0) res[1][29]=a24;
  a24=(a7*a12);
  a27=(a6*a14);
  a27=(a18+a27);
  a24=(a24-a27);
  a24=(a24+a17);
  a24=(a24+a10);
  if (res[1]!=0) res[1][30]=a24;
  a24=(a2*a14);
  a24=(a24-a22);
  a24=(a24+a19);
  a27=(a7*a9);
  a24=(a24-a27);
  a24=(a24+a15);
  if (res[1]!=0) res[1][31]=a24;
  a24=(a2*a12);
  a5=(a5-a24);
  a24=(a6*a9);
  a5=(a5+a24);
  a5=(a5+a16);
  if (res[1]!=0) res[1][32]=a5;
  a18=(a18-a17);
  a18=(a18-a10);
  if (res[1]!=0) res[1][33]=a18;
  a22=(a22-a19);
  a22=(a22-a15);
  if (res[1]!=0) res[1][34]=a22;
  a23=(a23-a20);
  a23=(a23-a16);
  if (res[1]!=0) res[1][35]=a23;
  if (res[1]!=0) res[1][36]=a9;
  if (res[1]!=0) res[1][37]=a12;
  if (res[1]!=0) res[1][38]=a14;
  a23=(a3*a14);
  a22=(a4*a12);
  a23=(a23-a22);
  if (res[1]!=0) res[1][39]=a23;
  a23=(a4*a9);
  a22=(a1*a14);
  a23=(a23-a22);
  if (res[1]!=0) res[1][40]=a23;
  a23=(a1*a12);
  a22=(a3*a9);
  a23=(a23-a22);
  if (res[1]!=0) res[1][41]=a23;
  a9=(-a9);
  if (res[1]!=0) res[1][42]=a9;
  a12=(-a12);
  if (res[1]!=0) res[1][43]=a12;
  a14=(-a14);
  if (res[1]!=0) res[1][44]=a14;
  a21=(a21+a17);
  a17=(a10-a21);
  if (res[1]!=0) res[1][45]=a17;
  a25=(a25+a19);
  a19=(a15-a25);
  if (res[1]!=0) res[1][46]=a19;
  a26=(a26+a20);
  a20=(a16-a26);
  if (res[1]!=0) res[1][47]=a20;
  a21=(a21-a10);
  a10=(a6*a13);
  a10=(a21+a10);
  a20=(a7*a11);
  a10=(a10-a20);
  if (res[1]!=0) res[1][48]=a10;
  a25=(a25-a15);
  a15=(a2*a13);
  a15=(a25-a15);
  a7=(a7*a8);
  a15=(a15+a7);
  if (res[1]!=0) res[1][49]=a15;
  a26=(a26-a16);
  a2=(a2*a11);
  a2=(a26+a2);
  a6=(a6*a8);
  a2=(a2-a6);
  if (res[1]!=0) res[1][50]=a2;
  if (res[1]!=0) res[1][51]=a21;
  if (res[1]!=0) res[1][52]=a25;
  if (res[1]!=0) res[1][53]=a26;
  if (res[1]!=0) res[1][54]=a8;
  if (res[1]!=0) res[1][55]=a11;
  if (res[1]!=0) res[1][56]=a13;
  a26=(a4*a11);
  a25=(a3*a13);
  a26=(a26-a25);
  if (res[1]!=0) res[1][57]=a26;
  a26=(a1*a13);
  a4=(a4*a8);
  a26=(a26-a4);
  if (res[1]!=0) res[1][58]=a26;
  a3=(a3*a8);
  a1=(a1*a11);
  a3=(a3-a1);
  if (res[1]!=0) res[1][59]=a3;
  a8=(-a8);
  if (res[1]!=0) res[1][60]=a8;
  a11=(-a11);
  if (res[1]!=0) res[1][61]=a11;
  a13=(-a13);
  if (res[1]!=0) res[1][62]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dae_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dae_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dae_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dae_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dae_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void dae_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dae_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dae_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real dae_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dae_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dae_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dae_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dae_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dae_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dae_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
