/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) NMPC_model_cost_y_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s1[3] = {0, 0, 0};

/* NMPC_model_cost_y_e_fun:(i0[24],i1[],i2[],i3[],i4[])->(o0[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=arg[0]? arg[0][0] : 0;
  a1=10.;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a1=0.;
  if (res[0]!=0) res[0][4]=a1;
  a2=arg[0]? arg[0][3] : 0;
  a3=(-a2);
  if (res[0]!=0) res[0][5]=a3;
  a3=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][6]=a3;
  a4=arg[0]? arg[0][6] : 0;
  a5=(-a4);
  if (res[0]!=0) res[0][7]=a5;
  if (res[0]!=0) res[0][8]=a1;
  a5=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a5;
  a6=arg[0]? arg[0][9] : 0;
  a7=(-a6);
  if (res[0]!=0) res[0][10]=a7;
  if (res[0]!=0) res[0][11]=a1;
  a1=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a1;
  a1=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a1;
  a1=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a1;
  a1=arg[0]? arg[0][15] : 0;
  a7=arg[0]? arg[0][4] : 0;
  a8=(a7*a2);
  a1=(a1-a8);
  if (res[0]!=0) res[0][15]=a1;
  a1=arg[0]? arg[0][16] : 0;
  a8=casadi_sq(a0);
  a2=casadi_sq(a2);
  a8=(a8+a2);
  a1=(a1+a8);
  if (res[0]!=0) res[0][16]=a1;
  a1=arg[0]? arg[0][17] : 0;
  a7=(a7*a0);
  a1=(a1-a7);
  if (res[0]!=0) res[0][17]=a1;
  a1=arg[0]? arg[0][18] : 0;
  a7=arg[0]? arg[0][8] : 0;
  a0=(a7*a4);
  a1=(a1+a0);
  if (res[0]!=0) res[0][18]=a1;
  a1=arg[0]? arg[0][19] : 0;
  a7=(a7*a3);
  a1=(a1+a7);
  if (res[0]!=0) res[0][19]=a1;
  a1=arg[0]? arg[0][20] : 0;
  a3=casadi_sq(a3);
  a4=casadi_sq(a4);
  a3=(a3+a4);
  a1=(a1-a3);
  if (res[0]!=0) res[0][20]=a1;
  a1=arg[0]? arg[0][21] : 0;
  a3=arg[0]? arg[0][11] : 0;
  a4=(a3*a6);
  a1=(a1+a4);
  if (res[0]!=0) res[0][21]=a1;
  a1=arg[0]? arg[0][22] : 0;
  a3=(a3*a5);
  a1=(a1+a3);
  if (res[0]!=0) res[0][22]=a1;
  a1=arg[0]? arg[0][23] : 0;
  a5=casadi_sq(a5);
  a6=casadi_sq(a6);
  a5=(a5+a6);
  a1=(a1-a5);
  if (res[0]!=0) res[0][23]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_y_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_y_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_y_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void NMPC_model_cost_y_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_y_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void NMPC_model_cost_y_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void NMPC_model_cost_y_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void NMPC_model_cost_y_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int NMPC_model_cost_y_e_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int NMPC_model_cost_y_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real NMPC_model_cost_y_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* NMPC_model_cost_y_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* NMPC_model_cost_y_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* NMPC_model_cost_y_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* NMPC_model_cost_y_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_y_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int NMPC_model_cost_y_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
