/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) geo_cost_y_0_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s4[69] = {30, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 18, 18, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 22, 23, 21, 23, 21, 22, 25, 26, 24, 26, 24, 25, 28, 29, 27, 29, 27, 28, 10, 11, 9, 11, 9, 10, 13, 14, 12, 14, 12, 13, 16, 17, 15, 17, 15, 16};

/* geo_cost_y_0_hess:(i0[24],i1[6],i2[],i3[18],i4[],i5[])->(o0[30x30,36nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][8] : 0;
  a1=arg[3]? arg[3][11] : 0;
  a2=(a0-a1);
  a3=(-a2);
  if (res[0]!=0) res[0][0]=a3;
  a4=arg[3]? arg[3][7] : 0;
  a5=arg[3]? arg[3][10] : 0;
  a6=(a4-a5);
  if (res[0]!=0) res[0][1]=a6;
  if (res[0]!=0) res[0][2]=a2;
  a7=arg[3]? arg[3][6] : 0;
  a8=arg[3]? arg[3][9] : 0;
  a9=(a7-a8);
  a10=(-a9);
  if (res[0]!=0) res[0][3]=a10;
  a11=(-a6);
  if (res[0]!=0) res[0][4]=a11;
  if (res[0]!=0) res[0][5]=a9;
  if (res[0]!=0) res[0][6]=a0;
  a12=(-a4);
  if (res[0]!=0) res[0][7]=a12;
  a13=(-a0);
  if (res[0]!=0) res[0][8]=a13;
  if (res[0]!=0) res[0][9]=a7;
  if (res[0]!=0) res[0][10]=a4;
  a14=(-a7);
  if (res[0]!=0) res[0][11]=a14;
  if (res[0]!=0) res[0][12]=a1;
  a15=(-a5);
  if (res[0]!=0) res[0][13]=a15;
  a16=(-a1);
  if (res[0]!=0) res[0][14]=a16;
  if (res[0]!=0) res[0][15]=a8;
  if (res[0]!=0) res[0][16]=a5;
  a17=(-a8);
  if (res[0]!=0) res[0][17]=a17;
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a11;
  if (res[0]!=0) res[0][20]=a3;
  if (res[0]!=0) res[0][21]=a9;
  if (res[0]!=0) res[0][22]=a6;
  if (res[0]!=0) res[0][23]=a10;
  if (res[0]!=0) res[0][24]=a13;
  if (res[0]!=0) res[0][25]=a4;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a14;
  if (res[0]!=0) res[0][28]=a12;
  if (res[0]!=0) res[0][29]=a7;
  if (res[0]!=0) res[0][30]=a16;
  if (res[0]!=0) res[0][31]=a5;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a17;
  if (res[0]!=0) res[0][34]=a15;
  if (res[0]!=0) res[0][35]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int geo_cost_y_0_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int geo_cost_y_0_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int geo_cost_y_0_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void geo_cost_y_0_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int geo_cost_y_0_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void geo_cost_y_0_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void geo_cost_y_0_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void geo_cost_y_0_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int geo_cost_y_0_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int geo_cost_y_0_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real geo_cost_y_0_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* geo_cost_y_0_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* geo_cost_y_0_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* geo_cost_y_0_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* geo_cost_y_0_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int geo_cost_y_0_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int geo_cost_y_0_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
